### ISSUE TITLE
ArcGIS support?

### ISSUE THREAD

**Issue by VolleyballCALVA** [stackTom/FSEarthTiles#11]
Good day, thank you very much for this useful tool.
Since the ArcGIS seems to be the most up-to-date satellite image with no terrain deformation, is it possible to add them as a image provider? Thank you.

Best Regards,
V. Liu

**Comment by stackTom** [comment]
Glad you like it. Arc gis is already supported. Just go to the following folder: Providers > Global. Use a text editor like notepad to open the Arc.lay file. In side this file, paste this line

in_GUI=True

Restart FSET and you will have Arcgis as an option.

**Comment by VolleyballCALVA** [comment]
Works great! Thank you very much.
