### ISSUE TITLE
 OSM server MAP rejected our query, new tentative in 2 sec...

### ISSUE THREAD

**Issue by virtualjotta** [stackTom/FSEarthTiles#13]
OSM server MAP rejected our query, new tentative in 2 sec...

**Comment by stackTom** [comment]
Open street map (OSM) doesn't allow for many downloads from their servers. Currently, I use a small subset of Ortho4XP to create the water masks. Ortho4XP downloads a lot of data from OSM, which is unnecessary for microsoft simulators. I am in the process of writing my own, custom water masking code which will only download the necessary data. This has the side effect of eliminating these "rejected our query" errors. I will release it whenever it is ready (It is approaching that stage). I've attached the current beta if you want to try it. Or, you can build it yourself by switching to the AutomaticWaterMasking branch of this repository.
[FSET.zip](https://github.com/stackTom/FSEarthTiles/files/11069214/FSET.zip)

Let me know if you try it and find any bugs.

**Comment by stackTom** [comment]
Here is a recent beta build of the new AutomaticWaterMasking. Try it out, and let me know how it goes:
[FSET.zip](https://github.com/stackTom/FSEarthTiles/files/11069603/FSET.zip)

**Comment by virtualjotta** [comment]
perfect! I'll try. Can I take the opportunity and ask a question? I wanted to redo the photoreal of my whole country, I live in Brazil, but that would take thousands of hours in processing, wouldn't it? even if it's in 8 quality... any alternative to generate the photoreal of an entire country without taking too much time? I know there is Tileproxy which would be more economical in time, but it doesn't make night masks. Thanks!

**Comment by stackTom** [comment]
Released the new water masking. Find it here: https://github.com/stackTom/FSEarthTiles/releases/tag/v2.0.0

It should eliminate your IP being throttled by OSM.
