### ISSUE TITLE
Black zones after KML use

### ISSUE THREAD

**Issue by Sgambe33** [stackTom/FSEarthTiles#15]
I tried selecting a zone with Google Earth like this:
![image](https://github.com/stackTom/FSEarthTiles/assets/80386324/a327482d-a849-4d7b-a2fb-b1797c054a7c)
Once the scenery has been compiled the result is a jagged scenery with black spots:
![image](https://github.com/stackTom/FSEarthTiles/assets/80386324/2dee571f-1baa-4818-913a-ed9bcbb9efad)
Now, I probably did something wrong while testing, but I can't find a way to exclude those black areas and have a smoother area.
Have any idea of what I am missing? Thanks for the help

**Comment by stackTom** [comment]
I haven't touched the code for KML files, so I will have to look into this. The code is the original code that HB-100 created.

However, any particular reason you are using KML files? The program now supports water masking automatically, without the use of kml files.

**Comment by Sgambe33** [comment]
I managed to remove the black squares and have a smooth area. I use KML files because I need a specific area that cannot be contained in a rectangle otherwise it would be sorrounded by white squares

**Comment by stackTom** [comment]
Oh, I see. I didn't even know FSET had this feature with kml files.

**Comment by Sgambe33** [comment]
Yeah, it's pretty neat but I need to do the same area twice to use automatic water masking

**Comment by stackTom** [comment]
Yes, this is because I made the program use automatic water masking OR the KML file. This is because I thought KML files could only be used to define water masks. I didn't know KML files had this feature of creating custom shaped areas, so I'll have to make it such that both KML files and automatic water masking can be used.

**Comment by stackTom** [comment]
How did you fix the black areas by the way? I would like to expand on this feature and make it compatible with the automatic water masking.

**Comment by Sgambe33** [comment]
In the AreaKML you Need to have 3 polygons: Area, LandPool and Water pool.
- Area: covers all the bounding box of the area of interest.
- LandPool: represents your area of interest and can be any size and any shape as long as is contained in Area.
- WaterPool: is the extension on the watermarsk. To only keep what you actually need, it needs to be bigger than the Area.

It basically applies a watermask everywhere where there is no LandPool.

**Comment by stackTom** [comment]
By the way, I have added support for custom borders/shaped areas. Will be released soon. It works seamlessly with automatic water masking now and doesn't require any workarounds.

**Comment by stackTom** [comment]
Custom borders are now officially supported while using automatic water masking. Download the latest version. Instructions are found in the quickstart included in the zip, or here : https://github.com/stackTom/FSEarthTiles/blob/main/FSEarthTiles/Docs/Quick%20start%20-%20README%20first%20(FS2004%2C%20FSX%2C%20P3D).docx
