### ISSUE TITLE
ScenProc

### ISSUE THREAD

**Issue by perficad** [stackTom/FSEarthTiles#26]
Hi there - Scenproc does not work in the latest version , so i have rolled back to 2.06, which was last stable with both watermasks working and scenproc.

**Comment by stackTom** [comment]
Hi, do you see any errors? It should work with 2.08 as I haven't modified the scenproc code for a while now.

Can you try your fsearthtiles.ini from 2.06 into 2.08 and see if it works?

**Comment by Artpom** [comment]
For me it works - v2.08

**Comment by perficad** [comment]
Hi again - thanks for the replies - despite it not working all of yesterday - I have just given 2.08 another go and now ScenProc seems to be working today - very strange!

**Comment by stackTom** [comment]
FSET just calls scenproc and passes it the default scripts and data. It really does nothing else so it scenproc is crashing etc, probably a scenproc issue :). The developer, Arno, is very good at answering questions in fsdeveloper forum. To me, scenproc is just black magic as I have no idea how it works nor how to create scripts for it.
