### ISSUE TITLE
JIT debugging

### ISSUE THREAD

**Issue by fdomatias** [stackTom/FSEarthTiles#29]
**Hello, good evening,
I wanted to report this incident that I have in some areas of several countries. I get the JIT Debugging error and I don't know how to fix it.**

See the end of this message for more details on how to invoke Just-In-Time (JIT) debugging instead of this dialog box.

************** Exception Text ************** System.Exception: Unknown way relation in AutomaticWaterMasking.WaterMasking.DrawInlandPolys(List`1 polys, Bitmap bmp, Graphics g, Point NW, Decimal pixelsPerLon, Decimal pixelsPerLat) in AutomaticWaterMasking.WaterMasking.GetMask(Dictionary`2 allMaskingPolys, Int32 pixelsX, Int32 pixelsY, Point NW , Decimal pixelsPerLon, Decimal pixelsPerLat, Graphics g, Bitmap bmp) in FSEarthTilesDLL.FSEarthTilesForm.AreaAllWater() in G:\FSEarthTiles\FSEarthTiles\FSEarthTilesDLL\FSEarthTilesForm.cs:line 9544 in FSEarthTilesDLL.FSEarthTilesForm.MainThreadTimerEventProcessor(Object myObject, EventArgs myEventArgs) in G:\FSEarthTiles\FSEarthTiles\FSEarthTilesDLL\FSEarthTilesForm.cs:line 7653 in System.Windows.Forms.Timer.OnTick(EventArgs e) in System.W indows.Forms.Timer.TimerNativeWindow.WndProc(Message& m) in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) ************** Loaded Assemblies ************** mscorlib Assembly Version: 4.0.0.0 Win Version 32: 4.8.9261.0 built by: NET481REL1LAST_C
Base code: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FSEarthTiles
Assembly version: 2.0.9.0
Win32 version: 2.0.9.0
Base code: file:///G:/FSET/FSEarthTiles.exe
----------------------------------------
System.Windows.Forms
Assembly version: 4.0.0.0
Win32 version: 4.8.9251.0 built by: NET481REL1LAST_C
Base code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll ---------------------------------------- System Assembly version: 4.0.0.0 Win32 version: 4.8. 9261.0 built by: NET481REL1LAST_C Code base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll ---------------------------------------- System.Drawing Assembly version: 4.0.0.0 Win3 version 2: 4.8.9037.0 built by: NET481REL1
Base code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
FSEarthTilesDLL
Assembly version: 2.0.9.0
Win32 version: 2.0.9.0
Base code: file:///G:/FSET/FSEarthTilesDLL.DLL
----------------------------------------
FSEarthTilesInternalDLL
Assembly version: 2.0.9.0
Win32 version: 2.0.9.0
Base code: file:///G:/FSET/FSEarthTilesInternalDLL.DLL
----------------------------------------
System.Configuration
Assembly version: 4.0.0.0
Win32: 4.8.9037.0 built by: NET481REL1 Code base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll ---------------------------------------- System.Core Assembly version : 4.0.0.0 Win32 version: 4.8.9261.0 built by: NET481REL1LAST_C Code base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll - System.Xml Assembly version: 4.0.0.0
Win32 version: 4.8.9037.0 built by: NET481REL1
Base code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
AutomaticWaterMasking
Assembly version: 1.0.0.0
Win32 version: 1.0.0.0
Base code: file:///G:/FSET/AutomaticWaterMasking.DLL
----------------------------------------
CSScriptLibrary
Assembly version: 2.0.0.0
Win32 version: 2.0.0.0
Base code: file:///G:/FSET/CSScriptLibrary.DLL
----------------------------------------
System.Drawing.resources
Assembly version: 1.0.0.0
Win32 version: 1.0.0.0
Base code: file:///G:/FSET/CSScriptLibrary.DLL
----------------------------------------
System.Drawing.resources ...1.0.0.0
Win32 version: 1.0.0.0
Base code: file:///G:/FSET/CSScriptLibrary.DLL
----------------------------------------
System.Drawing.resources
Assembly version: 1.0.0.0
Win32 version: 1.0.0.0
Base assembly: 4.0.0.0
Win32 version: 4.8.9037.0 built by: NET481REL1
Base code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.resources/v4.0_4.0.0.0_en_b03f5f7f11d50a3a/System.Drawing.resources.dll
----------------------------------------
mscorlib.resources
Assembly version: 4.0.0.0
Win32 version: 4.8.9037.0 built by: NET481REL1
Base code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_en_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
2cd24348-80ea-4950-9c67-caf07de881f4
Assembly version: 0.0.0.0
Win32 version: 0.0.0.0
Base code: file:///C:/Users/user/AppData/Local/Temp/2cd24348-80ea-4950-9c67-caf07de881f4.tmp
----------------------------------------
40cf54ff-7362-4fc7-b508-d43e4b1a2c84
Assembly version: 0.0.0.0 Win32 Version: 0.0.0.0 Code Base: file:///C:/Users/user/AppData/Local/Temp/40cf54ff-7362-4fc7-b508-d43e4b1a2c84.tmp
----------------------------------------
b3656249-10ad-4da9-b25c-e98a915223f5
Assembly version: 0.0.0.0
Win32 version: 0.0.0.0
Base code: file:///C:/Users/user/AppData/Local/Temp/b3656249-10ad-4da9-b25c-e98a915223f5.tmp
----------------------------------------
System.Windows.Forms.resources
Assembly version: 4.0.0.0
Win32 version: 4.8.9037.0 built by: NET481REL1
Base code: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_en_US_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT Debugging **************
To enable Just In Time (JIT) debugging, the configuration file for this application or computer (machine.config) must have the jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled

For example:

<configuration>
<system.windows.forms jitDebugging="true" />
</configuration>

**Comment by stackTom** [comment]
Export the partialfsearthtiles.ini so I can see which area this is happening in. This happens when someone encodes data incorrectly in openstreetmap. I made it so FSET just crashes with this error. Which is bad design. At some point, I will make it so it tells you which way is encoded wrongly (without crashing) so you can go on openstreetmap and fix the way.

**Comment by fdomatias** [comment]
Hello, thanks for the quick response, I am sending the file, it has happened to me in several places.

https://drive.google.com/drive/folders/1kY5b42E4JRyzyO9wPvSTjn3MsgBi4EKI?usp=sharing

I look forward to your help.

**Comment by fdomatias** [comment]
Hi @stackTom do you have any solution to this problem? Thanks. Regards

**Comment by stackTom** [comment]
Hi, I will try to look today or tomorrow. I'll also make FSET give a more informative error rather than just crashing.

**Comment by stackTom** [comment]
Okay, I upgraded the program to v2.1.0. It will now show an error message showing which way is badly encoded in OSM, so that users can fix it in OSM.
Please upgrade the program. Also, please delete this folder inside the Tiles folder (inside your working folder). +30+104

Then, restart the scenery creation. It should work, as I have fixed the corrupt data in OSM.
