### ISSUE TITLE
3m/Pix

### ISSUE THREAD

**Issue by Artpom** [stackTom/FSEarthTiles#30]
Hi, question/request - is it possible to implement 3m/Pix resolution, as 2m/Pix it takes too much resource and time, and 4m/Pix is too blurry. I think 3m/Pix would be a sweet spot between quality and required calculation time - what do you think?

**Comment by stackTom** [comment]
This is more a limitation of how mapping servers work. I don't believe it's possible to do this: https://learn.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system?redirectedfrom=MSDN
