### ISSUE TITLE
Future of Bing?

### ISSUE THREAD

**Issue by davidk64fnq** [stackTom/FSEarthTiles#33]
Just wondering what the future will be with Bing moving to subscription based? Are there good alternatives that remain free and don't have watermarks?

**Comment by stackTom** [comment]
Yes. Have a look at the lay files in the Providers folder. Open any of these with a text editor, and change in_GUI=False to in_GUI=True.

These providers are from Ortho4XP. Most Ortho4XP providers are supported. There's many forum posts online about which are good or not👍.

**Comment by davidk64fnq** [comment]
Thanks - good news
